import { useCallback, useEffect, useMemo, useState } from "react";
import Navbar from "../../components/homeNavbar";
import Coin from "../../assets/coin.png";
import { apiRequest, cacheWallet } from "../../services/api";

const networks=["MTN","AIRTEL","GLO","9MOBILE"];
const money=minor=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(Number(minor||0)/100);
const statusClass={successful:"bg-emerald-100 text-emerald-700",pending:"bg-amber-100 text-amber-700",refunded:"bg-blue-100 text-blue-700",failed:"bg-red-100 text-red-700"};

export default function Airtime(){
 const [data,setData]=useState(null),[balance,setBalance]=useState(0),[form,setForm]=useState({phone:"",network:"MTN",amount:""}),[loading,setLoading]=useState(true),[buying,setBuying]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [airtime,wallet]=await Promise.all([apiRequest("/airtime?limit=100"),apiRequest("/coins/me")]);setData(airtime);setBalance(Number(wallet.balance||0))}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const settings=data?.settings,cost=useMemo(()=>Math.round(Number(form.amount||0)*Number(settings?.points_per_naira||0)),[form.amount,settings]);
 const submit=async e=>{e.preventDefault();setBuying(true);setError("");setNotice("");try{const result=await apiRequest("/airtime/redemptions",{method:"POST",body:JSON.stringify({phone:form.phone,network:form.network,amount:Number(form.amount),clientReference:crypto.randomUUID()})});setNotice(`${money(result.redemption.amount_minor)} airtime was sent to ${result.redemption.phone}.`);setForm(x=>({...x,amount:""}));await load();cacheWallet({coins_count:balance-cost});window.dispatchEvent(new Event("cedugames:wallet-updated"))}catch(e){setError(e.message);await load()}finally{setBuying(false)}};
 return <div className="min-h-screen bg-slate-100"><Navbar/><main className="mx-auto w-full max-w-6xl p-3 sm:p-6"><section className="overflow-hidden rounded-3xl bg-white shadow-sm"><header className="bg-gradient-to-br from-purple-600 to-violet-800 px-5 py-8 text-white sm:px-9"><p className="text-sm font-bold uppercase tracking-widest text-purple-200">Points to airtime</p><h1 className="mt-2 text-3xl font-black">Turn learning rewards into airtime</h1><p className="mt-2 max-w-2xl text-purple-100">Choose a Nigerian network, enter the recipient number and review the exact point cost before confirming.</p><div className="mt-5 inline-flex items-center gap-2 rounded-full bg-white/15 px-4 py-2 font-bold"><img src={Coin} alt="" className="h-7 w-7"/>{balance.toLocaleString()} points available</div></header>
 {loading?<div className="py-24 text-center text-slate-400">Loading airtime wallet...</div>:<div className="grid gap-7 p-4 sm:p-8 lg:grid-cols-[minmax(0,420px)_1fr]"> <form onSubmit={submit} className="h-fit rounded-2xl border border-purple-100 bg-purple-50/40 p-5"><h2 className="text-xl font-black">Buy airtime</h2>{settings?.is_enabled?<><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-2">{networks.map(n=><button type="button" key={n} onClick={()=>setForm(x=>({...x,network:n}))} className={`rounded-xl border px-3 py-3 text-sm font-black ${form.network===n?"border-purple-600 bg-purple-600 text-white":"bg-white text-slate-600"}`}>{n}</button>)}</div><label className="mt-5 block text-sm font-bold">Phone number<input required inputMode="tel" placeholder="08012345678" value={form.phone} onChange={e=>setForm(x=>({...x,phone:e.target.value}))} className="mt-1 w-full rounded-xl border bg-white px-4 py-3 outline-none focus:border-purple-500"/></label><label className="mt-4 block text-sm font-bold">Airtime amount (NGN)<input required type="number" step="1" min={Number(settings.minimum_amount_minor)/100} max={Number(settings.maximum_amount_minor)/100} value={form.amount} onChange={e=>setForm(x=>({...x,amount:e.target.value}))} className="mt-1 w-full rounded-xl border bg-white px-4 py-3 outline-none focus:border-purple-500"/><span className="mt-1 block text-xs font-normal text-slate-400">From {money(settings.minimum_amount_minor)} to {money(settings.maximum_amount_minor)}</span></label><div className="mt-5 rounded-xl bg-white p-4"><div className="flex justify-between text-sm"><span>Airtime value</span><b>{money(Number(form.amount||0)*100)}</b></div><div className="mt-2 flex justify-between text-sm"><span>Conversion rate</span><b>{Number(settings.points_per_naira).toLocaleString()} points / NGN 1</b></div><div className="mt-3 flex justify-between border-t pt-3"><span className="font-bold">Total cost</span><b className={cost>balance?"text-red-600":"text-purple-700"}>{cost.toLocaleString()} points</b></div></div><button disabled={buying||!cost||cost>balance} className="mt-5 w-full rounded-xl bg-purple-600 px-4 py-3 font-black text-white disabled:cursor-not-allowed disabled:opacity-50">{buying?"Sending airtime...":"Confirm purchase"}</button></>:<div className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-700">Airtime redemption is currently paused. Your points remain safe.</div>}{error&&<div role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}</form>
 <section><div><h2 className="text-xl font-black">Your airtime history</h2><p className="text-sm text-slate-500">Every request keeps its original rate, recipient, status and references.</p></div>{data?.redemptions?.length?<div className="mt-5 space-y-3">{data.redemptions.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-slate-900">{money(r.amount_minor)} · {r.network}</p><p className="text-sm text-slate-500">{r.phone} · {new Date(r.created_at).toLocaleString()}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${statusClass[r.status]||"bg-slate-100"}`}>{r.status}</span></div><div className="mt-3 grid gap-1 text-xs text-slate-500 sm:grid-cols-2"><p><b className="text-slate-700">Points:</b> {Number(r.points_used).toLocaleString()} at {r.points_per_naira}/NGN</p><p className="break-all"><b className="text-slate-700">Reference:</b> {r.reference}</p>{r.provider_reference&&<p className="break-all"><b className="text-slate-700">Provider:</b> {r.provider_reference}</p>}{r.failure_reason&&<p className="text-red-600"><b>Reason:</b> {r.failure_reason}</p>}</div></article>)}</div>:<div className="mt-5 rounded-2xl border-2 border-dashed p-12 text-center text-slate-400">No airtime purchases yet.</div>}</section></div>}
 </section></main></div>;
}
