import BG from "../../assets/BG.png";
import Navbar from "../../components/homeNavbar";
import {useCallback,useEffect,useRef,useState} from "react";
import {useNavigate,useSearchParams} from "react-router-dom";
import {apiRequest,getLearningSelection,saveLearningSelection} from "../../services/api";

const melody=[523.25,659.25,783.99,659.25,587.33,698.46,783.99,0];
const horizontal=[50,39,54,42,55,63,61,51,43];

async function loadLevels(categoryId){
 try{return await apiRequest(`/gameplay/categories/${categoryId}/levels`)}
 catch(error){
  if(!/route not found/i.test(error.message))throw error;
  const legacy=await apiRequest(`/catalog/categories/${categoryId}/levels`);
  return{...legacy,levels:(legacy.levels||[]).map((level,index)=>({...level,best_score:0,completed:false,unlocked:index===0}))};
 }
}

export default function Home(){
 const navigate=useNavigate(),[params]=useSearchParams(),savedSelection=getLearningSelection(),queryCategoryId=params.get("category"),queryAgeId=params.get("ageGroup"),categoryId=queryCategoryId||savedSelection?.categoryId,ageId=queryAgeId||savedSelection?.ageGroupId;
 const[levels,setLevels]=useState([]),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(Boolean(categoryId)),[error,setError]=useState(categoryId?"":"Choose a subject before selecting a level."),[soundOn,setSoundOn]=useState(true);const audioRef=useRef(null),timerRef=useRef(null);
 const stop=useCallback(()=>{window.clearTimeout(timerRef.current);timerRef.current=null;if(audioRef.current){audioRef.current.close();audioRef.current=null}},[]);
 const start=useCallback(()=>{if(!soundOn||audioRef.current)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;const context=new AudioContext();audioRef.current=context;let index=0;const play=()=>{if(audioRef.current!==context)return;const frequency=melody[index%melody.length];if(frequency){const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.03,context.currentTime+.04);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.35);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.38)}index+=1;timerRef.current=window.setTimeout(play,460)};context.resume().then(play).catch(stop)},[soundOn,stop]);
 useEffect(()=>{if(!soundOn){stop();return undefined}window.addEventListener("pointerdown",start,{once:true});return()=>window.removeEventListener("pointerdown",start)},[soundOn,start,stop]);useEffect(()=>stop,[stop]);
 useEffect(()=>{if(!categoryId)return;loadLevels(categoryId).then(data=>{const found=data.levels||[];setLevels(found);const available=[...found].reverse().find(level=>level.unlocked);setSelectedId(available?.id||"")}).catch(requestError=>setError(requestError.message)).finally(()=>setLoading(false))},[categoryId]);
 useEffect(()=>{if(!ageId||!categoryId)return;saveLearningSelection(ageId,categoryId);if(!queryAgeId||!queryCategoryId)navigate(`/play?ageGroup=${ageId}&category=${categoryId}`,{replace:true})},[ageId,categoryId,queryAgeId,queryCategoryId,navigate]);
 const selected=levels.find(level=>level.id===selectedId),mapHeight=Math.max(520,levels.length*92+120),completedCount=levels.filter(level=>level.completed).length;
 return <div className="level-selection-page flex h-[100dvh] min-h-screen w-full flex-col overflow-hidden text-white" style={{backgroundImage:`url(${BG})`,backgroundSize:"cover",backgroundPosition:"center"}}><Navbar/>
 <main className="relative min-h-0 flex-1 overflow-y-auto overscroll-contain pb-28"><div className="sticky top-0 z-20 mx-auto mt-1 w-[calc(100%-0.75rem)] max-w-xl rounded-2xl border border-white/60 bg-white/95 p-2 text-slate-800 shadow-lg backdrop-blur sm:top-2 sm:mt-2 sm:p-3"><div className="flex items-center justify-between gap-2"><button onClick={()=>navigate(`/age-selection/little-explore?ageGroup=${ageId||""}`)} aria-label="Back to subjects" className="flex min-h-11 shrink-0 items-center rounded-xl border border-purple-300 bg-white px-3 py-2 text-xs font-black text-purple-700 sm:text-sm"><span aria-hidden="true">←</span><span className="ml-1 hidden min-[360px]:inline">Subjects</span></button><div className="min-w-0 flex-1 text-center"><p className="line-clamp-2 text-sm font-black leading-tight sm:text-lg">{selected?.name||"Choose a level"}</p>{selected&&<p className="mt-1 text-[10px] font-semibold leading-tight text-slate-500 sm:text-xs">Best {selected.best_score}% · {selected.time_limit_seconds}s each</p>}</div><span className="shrink-0 rounded-full bg-purple-100 px-2.5 py-2 text-xs font-black text-purple-700 sm:px-3 sm:text-sm" aria-label={`${completedCount} of ${levels.length} levels completed`}>{completedCount}/{levels.length}</span><button type="button" onClick={()=>setSoundOn(value=>!value)} aria-label={soundOn?"Turn music off":"Turn music on"} className="grid min-h-11 min-w-11 shrink-0 place-items-center rounded-xl bg-slate-800 text-lg text-white shadow-sm">{soundOn?"🔊":"🔇"}</button></div></div>
 {loading?<MapState text="Loading your learning path…"/>:error?<MapState text={error} error/>:levels.length?<div className="level-map relative mx-auto w-full max-w-4xl overflow-hidden" style={{height:mapHeight}}>{levels.map((level,index)=>{const isSelected=level.id===selectedId;return <button key={level.id} disabled={!level.unlocked} onClick={()=>setSelectedId(level.id)} style={{"--level-x":horizontal[index%horizontal.length],"--level-bottom":`${index*92+82}px`}} className={`level-map-node absolute z-10 grid h-[68px] w-[68px] place-items-center rounded-full border-[3px] text-center shadow-lg transition sm:h-[76px] sm:w-[76px] ${level.completed?"border-emerald-300 bg-emerald-50 text-emerald-800":level.unlocked?isSelected?"scale-110 border-purple-300 bg-purple-600 text-white ring-4 ring-white/40":"border-white bg-white/95 text-slate-800 hover:scale-105":"cursor-not-allowed border-white/80 bg-slate-200/90 text-slate-500"}`}><span><span className="block text-lg leading-none">{level.completed?"✓":level.unlocked?"★":"🔒"}</span><span className="mt-1 block text-[10px] font-black leading-none sm:text-xs">Level {level.level_number}</span></span></button>})}</div>:<MapState text="No levels are available for this subject yet."/>}
 </main><div className="level-play-bar fixed inset-x-0 bottom-0 z-30 flex justify-center bg-gradient-to-t from-slate-950/80 via-slate-900/50 to-transparent px-3 pb-[max(.75rem,env(safe-area-inset-bottom))] pt-8"><button disabled={!selected} onClick={()=>navigate(`/quiz?ageGroup=${ageId}&category=${categoryId}&level=${selected.id}`)} className="home-start-button min-h-12 w-full max-w-sm rounded-2xl bg-purple-600 px-5 py-3 text-base font-black text-white shadow-xl disabled:cursor-not-allowed disabled:opacity-50">{selected?`Play Level ${selected.level_number}`:"Select an unlocked level"}</button></div></div>;
}
function MapState({text,error=false}){return <div className={`mx-3 mt-16 max-w-md rounded-2xl p-6 text-center font-bold shadow-lg sm:mx-auto sm:mt-24 ${error?"bg-red-50 text-red-700":"bg-white/90 text-slate-600"}`}>{text}</div>}
