import BG from "../../assets/BG.png";
import Navbar from "../../components/homeNavbar";
import {useCallback,useEffect,useRef,useState} from "react";
import {useNavigate,useSearchParams} from "react-router-dom";
import {apiRequest,getLearningSelection,saveLearningSelection} from "../../services/api";

const melody=[523.25,659.25,783.99,659.25,587.33,698.46,783.99,0];
const horizontal=[50,39,54,42,55,63,61,51,43];

async function loadLevels(categoryId){
 try{return await apiRequest(`/gameplay/categories/${categoryId}/levels`)}
 catch(error){
  if(!/route not found/i.test(error.message))throw error;
  const legacy=await apiRequest(`/catalog/categories/${categoryId}/levels`);
  return{...legacy,levels:(legacy.levels||[]).map((level,index)=>({...level,best_score:0,completed:false,unlocked:index===0}))};
 }
}

export default function Home(){
 const navigate=useNavigate(),[params]=useSearchParams(),savedSelection=getLearningSelection(),queryCategoryId=params.get("category"),queryAgeId=params.get("ageGroup"),categoryId=queryCategoryId||savedSelection?.categoryId,ageId=queryAgeId||savedSelection?.ageGroupId;
 const[levels,setLevels]=useState([]),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(Boolean(categoryId)),[error,setError]=useState(categoryId?"":"Choose a subject before selecting a level."),[soundOn,setSoundOn]=useState(true);const audioRef=useRef(null),timerRef=useRef(null);
 const stop=useCallback(()=>{window.clearTimeout(timerRef.current);timerRef.current=null;if(audioRef.current){audioRef.current.close();audioRef.current=null}},[]);
 const start=useCallback(()=>{if(!soundOn||audioRef.current)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;const context=new AudioContext();audioRef.current=context;let index=0;const play=()=>{if(audioRef.current!==context)return;const frequency=melody[index%melody.length];if(frequency){const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.03,context.currentTime+.04);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.35);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.38)}index+=1;timerRef.current=window.setTimeout(play,460)};context.resume().then(play).catch(stop)},[soundOn,stop]);
 useEffect(()=>{if(!soundOn){stop();return undefined}window.addEventListener("pointerdown",start,{once:true});return()=>window.removeEventListener("pointerdown",start)},[soundOn,start,stop]);useEffect(()=>stop,[stop]);
 useEffect(()=>{if(!categoryId)return;loadLevels(categoryId).then(data=>{const found=data.levels||[];setLevels(found);const available=[...found].reverse().find(level=>level.unlocked);setSelectedId(available?.id||"")}).catch(requestError=>setError(requestError.message)).finally(()=>setLoading(false))},[categoryId]);
 useEffect(()=>{if(!ageId||!categoryId)return;saveLearningSelection(ageId,categoryId);if(!queryAgeId||!queryCategoryId)navigate(`/play?ageGroup=${ageId}&category=${categoryId}`,{replace:true})},[ageId,categoryId,queryAgeId,queryCategoryId,navigate]);
 const selected=levels.find(level=>level.id===selectedId),mapHeight=Math.max(500,levels.length*86+100);
 return <div className="flex min-h-screen w-full flex-col overflow-hidden text-white" style={{backgroundImage:`url(${BG})`,backgroundSize:"cover",backgroundPosition:"center"}}><Navbar/><button type="button" onClick={()=>setSoundOn(value=>!value)} aria-label={soundOn?"Turn music off":"Turn music on"} className="fixed right-3 top-32 z-30 grid h-11 w-11 place-items-center rounded-full bg-black/40 text-xl shadow-lg backdrop-blur sm:right-6 lg:top-24">{soundOn?"🔊":"🔇"}</button>
 <main className="relative flex-1 overflow-y-auto"><div className="sticky top-1 z-20 mx-auto mt-1 flex min-h-16 w-[calc(100%-0.75rem)] max-w-lg items-center justify-between gap-2 rounded-2xl border border-white/60 bg-white/90 px-2 py-2 text-slate-800 shadow-md backdrop-blur sm:top-2 sm:mt-2 sm:min-h-[72px] sm:max-w-xl sm:gap-3 sm:px-3"><button onClick={()=>navigate(`/age-selection/little-explore?ageGroup=${ageId||""}`)} aria-label="Back to subjects" className="flex shrink-0 items-center rounded-xl border border-purple-300 bg-white px-2.5 py-2 text-xs font-black text-purple-700 sm:px-3 sm:text-sm"><span aria-hidden="true">←</span><span> Subjects</span></button><div className="min-w-0 flex-1 text-center"><p className="truncate text-sm font-black sm:text-lg">{selected?.name||"Choose a level"}</p>{selected&&<p className="mt-0.5 truncate text-[10px] font-medium text-slate-500 sm:text-xs">Best score {selected.best_score}% · {selected.time_limit_seconds}s per question</p>}</div><span className="shrink-0 rounded-full bg-purple-100 px-2.5 py-2 text-xs font-black text-purple-700 sm:px-3 sm:text-sm" aria-label={`${levels.filter(level=>level.completed).length} of ${levels.length} levels completed`}>{levels.filter(level=>level.completed).length}/{levels.length}</span></div>
 {loading?<MapState text="Loading your learning path…"/>:error?<MapState text={error} error/>:levels.length?<div className="relative mx-auto w-full max-w-4xl" style={{height:mapHeight}}>{levels.map((level,index)=>{const isSelected=level.id===selectedId;return <button key={level.id} disabled={!level.unlocked} onClick={()=>setSelectedId(level.id)} style={{left:`calc(${horizontal[index%horizontal.length]}% - 32px)`,bottom:index*82+76}} className={`absolute z-10 grid h-16 w-16 place-items-center rounded-full border-[3px] text-center shadow-md transition sm:h-[72px] sm:w-[72px] ${level.completed?"border-emerald-300 bg-emerald-50 text-emerald-800":level.unlocked?isSelected?"scale-105 border-purple-400 bg-purple-600 text-white":"border-white bg-white/90 text-slate-800 hover:scale-105":"cursor-not-allowed border-white/80 bg-slate-200/85 text-slate-500"}`}><span><span className="block text-base">{level.completed?"✓":level.unlocked?"★":"🔒"}</span><span className="text-[10px] font-black sm:text-xs">Level {level.level_number}</span></span></button>})}</div>:<MapState text="No levels are available for this subject yet."/>}
 </main><div className="fixed inset-x-0 bottom-0 z-30 flex justify-center bg-gradient-to-t from-slate-900/50 to-transparent p-3 pt-8"><button disabled={!selected} onClick={()=>navigate(`/quiz?ageGroup=${ageId}&category=${categoryId}&level=${selected.id}`)} className="home-start-button w-full max-w-xs rounded-xl bg-purple-600 px-5 py-3 text-base font-black text-white shadow-xl disabled:cursor-not-allowed disabled:opacity-50">{selected?`Play Level ${selected.level_number}`:"Select an unlocked level"}</button></div></div>;
}
function MapState({text,error=false}){return <div className={`mx-auto mt-24 max-w-md rounded-2xl p-6 text-center font-bold shadow-lg ${error?"bg-red-50 text-red-700":"bg-white/90 text-slate-600"}`}>{text}</div>}
