import { useCallback, useEffect, useState } from "react";
import Navbar from "../../components/homeNavbar";
import LeaderboardIcon from "../../assets/leaderboard.png";
import { apiRequest, isSignedIn } from "../../services/api";

const periods=[{id:"all",label:"All time"},{id:"month",label:"Monthly"},{id:"week",label:"Weekly"}];
const points=(p,period)=>Number(period==="all"?p.total_xp:p.period_xp||0);
export default function Leaderboard(){
 const[players,setPlayers]=useState([]),[me,setMe]=useState(null),[period,setPeriod]=useState("all"),[page,setPage]=useState(1),[pagination,setPagination]=useState({total:0,limit:20}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const requests=[apiRequest(`/leaderboard?period=${period}&page=${page}&limit=20`)];if(isSignedIn())requests.push(apiRequest(`/leaderboard/me?period=${period}`));const[data,mine]=await Promise.all(requests);setPlayers(data.players||[]);setPagination(data.pagination||{});setMe(mine?.player||null)}catch(e){setError(e.message)}finally{setLoading(false)}},[period,page]);useEffect(()=>{load()},[load]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState!=="hidden")load()};const timer=window.setInterval(refresh,30000);window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",refresh);return()=>{window.clearInterval(timer);window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",refresh)}},[load]);
 const podium=players.slice(0,3),rest=players.slice(page===1?3:0);
 return <div><Navbar/><main className="min-h-screen bg-slate-100 p-3 sm:p-6"><section className="mx-auto max-w-6xl rounded-3xl bg-white p-4 shadow-sm sm:p-8"><img src={LeaderboardIcon} alt="Leaderboard" className="mx-auto mb-5 w-full max-w-xl"/><div className="mb-7 flex justify-center"><div className="flex rounded-xl bg-slate-100 p-1">{periods.map(p=><button key={p.id} onClick={()=>{setPeriod(p.id);setPage(1)}} className={`rounded-lg px-4 py-2 text-sm font-bold ${period===p.id?"bg-white text-purple-700 shadow":"text-slate-500"}`}>{p.label}</button>)}</div></div>
 {me&&<div className="mb-7 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-gradient-to-r from-purple-600 to-violet-500 p-5 text-white"><div><p className="text-xs font-bold uppercase text-white/70">Your position</p><p className="text-2xl font-black">#{me.rank} · {me.name}</p></div><div className="flex gap-6 text-center"><Metric label="XP" value={points(me,period).toLocaleString()}/><Metric label="Completed" value={me.completed_levels}/><Metric label="Average" value={`${me.average_score}%`}/></div></div>}
 {error?<div className="rounded-xl bg-red-50 p-5 text-center text-red-700">{error}</div>:loading?<div className="py-24 text-center text-slate-400">Loading leaderboard…</div>:<>{page===1&&podium.length>0&&<div className="mb-8 grid items-end gap-4 sm:grid-cols-3">{[podium[1],podium[0],podium[2]].filter(Boolean).map(p=><article key={p.id} className={`rounded-2xl p-5 text-center ${Number(p.rank)===1?"order-first bg-amber-50 ring-2 ring-amber-300 sm:order-none sm:py-8":"bg-slate-50"}`}><div className={`mx-auto grid h-16 w-16 place-items-center rounded-full text-2xl font-black ${Number(p.rank)===1?"bg-amber-400 text-white":"bg-purple-100 text-purple-700"}`}>{p.name?.[0]}</div><p className="mt-3 text-2xl font-black">#{p.rank}</p><h2 className="font-bold">{p.name}</h2><p className="text-sm text-slate-400">@{p.username}</p><p className="mt-2 font-black text-purple-700">{points(p,period).toLocaleString()} XP</p></article>)}</div>}<div className="overflow-hidden rounded-2xl border"><div className="grid grid-cols-[56px_1fr_auto] gap-3 bg-slate-50 px-4 py-3 text-xs font-bold uppercase text-slate-400 sm:grid-cols-[70px_1fr_120px_120px]"><span>Rank</span><span>Player</span><span className="hidden sm:block">Completed</span><span>XP</span></div>{rest.map(p=><div key={p.id} className={`grid grid-cols-[56px_1fr_auto] items-center gap-3 border-t px-4 py-4 sm:grid-cols-[70px_1fr_120px_120px] ${me?.id===p.id?"bg-purple-50":""}`}><b className="text-lg text-purple-700">#{p.rank}</b><div><p className="font-bold text-slate-900">{p.name}</p><p className="text-xs text-slate-400">Average {p.average_score}% · {p.attempts} attempts</p></div><span className="hidden sm:block">{p.completed_levels} levels</span><b className="text-right">{points(p,period).toLocaleString()}</b></div>)}</div><div className="mt-5 flex items-center justify-between text-sm text-slate-500"><span>{pagination.total||0} ranked players</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><button disabled={page*20>=(pagination.total||0)} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></div></>}
 </section></main></div>;
}
function Metric({label,value}){return <div><p className="text-xl font-black">{value}</p><p className="text-xs text-white/70">{label}</p></div>}
