import {useEffect,useState} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import NavItem from "./NavItem";
import Badge from "./badge";
import {apiRequest,cacheLearningSelection,cacheWallet,getCachedWallet,getLearningSelection,isSignedIn,USER_KEY} from "../services/api";

const iconPaths={
 home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/></>,
 gift:<><rect x="3" y="8" width="18" height="13" rx="2"/><path d="M12 8v13M3 12h18M7.5 8C5 8 4 6.5 4.8 5.1 6 3 9.7 5.2 12 8M16.5 8c2.5 0 3.5-1.5 2.7-2.9C18 3 14.3 5.2 12 8"/></>,
 trophy:<><path d="M8 4h8v5a4 4 0 0 1-8 0V4Z"/><path d="M8 6H4v2a4 4 0 0 0 4 4M16 6h4v2a4 4 0 0 1-4 4M12 13v4M8 21h8M9 17h6"/></>,
 shop:<><path d="M3 9h18l-2-5H5L3 9Z"/><path d="M5 9v11h14V9M9 20v-6h6v6"/><path d="M3 9a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0"/></>,
 user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,
};
function NavIcon({name}){return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{iconPaths[name]}</svg>}

export default function Navbar(){
 const location=useLocation(),navigate=useNavigate(),[wallet,setWallet]=useState(()=>getCachedWallet()),[user,setUser]=useState(()=>JSON.parse(localStorage.getItem(USER_KEY)||"null")),[unread,setUnread]=useState(0),[learningSelection,setLearningSelection]=useState(()=>getLearningSelection());
 useEffect(()=>{if(!isSignedIn())return undefined;let live=true;apiRequest("/auth/user/dashboard-bootstrap").then(data=>{if(!live)return;cacheWallet(data.wallet);setWallet(data.wallet);setUnread(Number(data.unreadCount||0));if(data.learningSelection){cacheLearningSelection(data.learningSelection);setLearningSelection(data.learningSelection)}if(data.user){localStorage.setItem(USER_KEY,JSON.stringify(data.user));setUser(data.user)}}).catch(()=>undefined);return()=>{live=false}},[]);
 useEffect(()=>{if(!isSignedIn())return undefined;let live=true;const load=()=>apiRequest("/gameplay/status").then(data=>{cacheWallet(data);if(live)setWallet(data)}).catch(()=>undefined);window.addEventListener("cedugames:wallet-updated",load);return()=>{live=false;window.removeEventListener("cedugames:wallet-updated",load)}},[]);
 useEffect(()=>{const loadUser=()=>setUser(JSON.parse(localStorage.getItem(USER_KEY)||"null"));window.addEventListener("cedugames:profile-updated",loadUser);return()=>window.removeEventListener("cedugames:profile-updated",loadUser)},[]);
 useEffect(()=>{if(!isSignedIn())return undefined;let live=true;const load=()=>apiRequest("/notifications?limit=1").then(data=>{if(live)setUnread(Number(data.unreadCount||0))}).catch(()=>undefined);window.addEventListener("cedugames:notifications-updated",load);return()=>{live=false;window.removeEventListener("cedugames:notifications-updated",load)}},[]);
 const homePath=learningSelection?`/play?ageGroup=${learningSelection.ageGroupId}&category=${learningSelection.categoryId}`:"/age-selection";
 const navItems=[{label:"Home",shortLabel:"Home",icon:"home",to:homePath},{label:"Daily reward",shortLabel:"Reward",icon:"gift",to:"/daily-reward"},{label:"Leaderboard",shortLabel:"Leaders",icon:"trophy",to:"/leaderboard"},{label:"Shop",shortLabel:"Shop",icon:"shop",to:"/shop"},{label:"Profile",shortLabel:"Profile",icon:"user",to:"/profile"}];
 const white=["/leaderboard","/shop","/profile","/notification","/daily-reward"].includes(location.pathname),text=white?"text-black":"text-white",bg=white?"bg-white":"bg-gradient-to-r from-purple-300/70 to-purple-400/60 backdrop-blur-md";
 const max=Number(wallet?.max_lives||0),lives=Number(wallet?.lives_remaining||0);
 return <header className={`w-full ${bg} flex flex-wrap items-center justify-between gap-3 rounded-none px-3 py-3 shadow-xl sm:rounded-xl sm:px-6 lg:flex-nowrap lg:px-8`}>
  <button type="button" onClick={()=>navigate("/profile")} aria-label="Open your profile" className="group flex items-center gap-3 rounded-xl p-1 text-left outline-none transition hover:bg-white/15 focus-visible:ring-2 focus-visible:ring-white/80"><span className="grid h-10 w-10 place-items-center rounded-full bg-purple-500 text-white transition group-hover:scale-105">👤</span><span><span className={`${text} block text-sm font-medium group-hover:underline`}>{user?.name||user?.username||"Player"}</span><span className={`block text-xs ${white?"text-gray-600":"text-white/70"}`}>Ready to play</span></span></button>
  <nav aria-label="Primary navigation" className={`order-3 grid w-full grid-cols-5 gap-1 border-t border-current/10 pt-3 sm:hidden ${text}`}>{navItems.map(item=>{const active=location.pathname===item.to.split("?")[0];return <button type="button" key={item.label} onClick={()=>navigate(item.to)} aria-current={active?"page":undefined} aria-label={item.label} className={`flex min-w-0 flex-col items-center gap-1 rounded-xl px-1 py-2 text-[11px] font-semibold outline-none transition focus-visible:ring-2 focus-visible:ring-current ${active?"bg-white/25 shadow-sm":"opacity-75 hover:bg-white/15 hover:opacity-100"}`}><NavIcon name={item.icon}/><span className="w-full truncate">{item.shortLabel}</span></button>})}</nav>
  <nav aria-label="Primary navigation" className={`order-3 hidden w-full items-center gap-4 border-t border-current/10 pt-3 text-sm font-medium sm:flex sm:justify-center lg:order-none lg:w-auto lg:gap-8 lg:border-0 lg:pt-0 ${text}`}>{navItems.map(item=><div key={item.label} className="shrink-0"><NavItem {...item} active={location.pathname===item.to.split("?")[0]} textColor={text} activeColor={text}/></div>)}</nav>
  <div className="flex items-center gap-2 sm:gap-4"><Badge>{wallet?<span aria-label={`${lives} of ${max} lives remaining`}>{Array.from({length:max},(_,index)=><span key={index} className={index<lives?"text-red-500":"text-white/70 grayscale"}>{index<lives?"♥":"♡"}</span>)}</span>:<span className="inline-block w-10 animate-pulse text-center opacity-50" aria-label="Loading lives">•••</span>}</Badge><Badge>🪙 {wallet?Number(wallet.coins_count||0).toLocaleString():"—"}</Badge><button aria-label={`Notifications${unread?`, ${unread} unread`:""}`} onClick={()=>navigate("/notification")} className={`relative grid h-10 w-10 place-items-center rounded-full ${white?"bg-gray-200":"bg-white/20"}`}>🔔{unread>0&&<span className="absolute -right-1 -top-1 grid min-h-5 min-w-5 place-items-center rounded-full bg-red-500 px-1 text-[10px] font-black text-white">{unread>99?"99+":unread}</span>}</button></div>
 </header>;
}
