import {useEffect,useState} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import NavItem from "./NavItem";
import Badge from "./badge";
import {apiRequest,assetUrl,cacheLearningSelection,cacheWallet,getCachedUser,getCachedWallet,isSignedIn,USER_KEY} from "../services/api";

const iconPaths={
 home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/></>,
 gift:<><rect x="3" y="8" width="18" height="13" rx="2"/><path d="M12 8v13M3 12h18M7.5 8C5 8 4 6.5 4.8 5.1 6 3 9.7 5.2 12 8M16.5 8c2.5 0 3.5-1.5 2.7-2.9C18 3 14.3 5.2 12 8"/></>,
 trophy:<><path d="M8 4h8v5a4 4 0 0 1-8 0V4Z"/><path d="M8 6H4v2a4 4 0 0 0 4 4M16 6h4v2a4 4 0 0 1-4 4M12 13v4M8 21h8M9 17h6"/></>,
 shop:<><path d="M3 9h18l-2-5H5L3 9Z"/><path d="M5 9v11h14V9M9 20v-6h6v6"/><path d="M3 9a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0"/></>,
 user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,
};
function NavIcon({name}){return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5 sm:h-6 sm:w-6" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{iconPaths[name]}</svg>}

export default function Navbar(){
 const location=useLocation(),navigate=useNavigate(),[wallet,setWallet]=useState(()=>getCachedWallet()),[user,setUser]=useState(()=>getCachedUser()),[unread,setUnread]=useState(0);
 useEffect(()=>{if(!isSignedIn())return undefined;let live=true;apiRequest("/auth/user/dashboard-bootstrap").then(data=>{if(!live)return;cacheWallet(data.wallet);setWallet(data.wallet);setUnread(Number(data.unreadCount||0));if(data.learningSelection)cacheLearningSelection(data.learningSelection);if(data.user){sessionStorage.setItem(USER_KEY,JSON.stringify(data.user));setUser(data.user)}}).catch(()=>undefined);return()=>{live=false}},[]);
 useEffect(()=>{if(!isSignedIn())return undefined;let live=true;const load=()=>apiRequest("/gameplay/status").then(data=>{cacheWallet(data);if(live)setWallet(data)}).catch(()=>undefined);window.addEventListener("cedugames:wallet-updated",load);return()=>{live=false;window.removeEventListener("cedugames:wallet-updated",load)}},[]);
 useEffect(()=>{const loadUser=()=>setUser(getCachedUser());window.addEventListener("cedugames:profile-updated",loadUser);return()=>window.removeEventListener("cedugames:profile-updated",loadUser)},[]);
 useEffect(()=>{if(!isSignedIn())return undefined;let live=true;const load=()=>apiRequest("/notifications?limit=1").then(data=>{if(live)setUnread(Number(data.unreadCount||0))}).catch(()=>undefined);window.addEventListener("cedugames:notifications-updated",load);return()=>{live=false;window.removeEventListener("cedugames:notifications-updated",load)}},[]);
 const navItems=[{label:"Home",shortLabel:"Home",icon:"home",to:"/profiles"},{label:"Daily reward",shortLabel:"Reward",icon:"gift",to:"/daily-reward"},{label:"Leaderboard",shortLabel:"Leaders",icon:"trophy",to:"/leaderboard"},{label:"Shop",shortLabel:"Shop",icon:"shop",to:"/shop"},{label:"Profile",shortLabel:"Profile",icon:"user",to:"/profile"}];
 const white=["/leaderboard","/shop","/profile","/notification","/daily-reward"].includes(location.pathname),text=white?"text-black":"text-white",bg=white?"bg-white":"bg-gradient-to-r from-purple-700/95 via-violet-600/95 to-fuchsia-600/90 backdrop-blur-md";
 const max=Number(wallet?.max_lives||0),lives=Number(wallet?.lives_remaining||0);
 return <header className={`w-full ${bg} flex flex-wrap items-center justify-between gap-x-1 gap-y-2 rounded-none px-2 py-2 shadow-xl sm:gap-3 sm:rounded-xl sm:px-6 sm:py-3 lg:flex-nowrap lg:px-8`}>
  <button type="button" onClick={()=>navigate("/profile")} aria-label="Open your profile" className="group flex min-w-0 items-center gap-2 rounded-xl p-1 text-left outline-none transition hover:bg-white/15 focus-visible:ring-2 focus-visible:ring-white/80 sm:gap-3"><span className="grid h-9 w-9 shrink-0 overflow-hidden rounded-full bg-purple-500 text-white transition group-hover:scale-105 sm:h-10 sm:w-10">{user?.profile_image_url?<img src={assetUrl(user.profile_image_url)} alt="" className="h-full w-full object-cover"/>:<span className="grid h-full w-full place-items-center" aria-hidden="true">👤</span>}</span><span className="min-w-0"><span className={`${text} block max-w-28 truncate text-xs font-bold group-hover:underline sm:max-w-none sm:text-sm sm:font-medium`}>{user?.name||user?.username||"Player"}</span><span className={`block text-[10px] sm:text-xs ${white?"text-gray-600":"text-white/70"}`}>Ready to play</span></span></button>
  <nav aria-label="Primary navigation" className={`order-3 grid w-full grid-cols-5 gap-0.5 border-t border-current/10 pt-1.5 sm:hidden ${text}`}>{navItems.map(item=>{const active=location.pathname===item.to.split("?")[0];return <button type="button" key={item.label} onClick={()=>navigate(item.to)} aria-current={active?"page":undefined} aria-label={item.label} className={`flex min-w-0 flex-col items-center gap-0.5 rounded-lg px-0.5 py-1.5 text-[10px] font-semibold outline-none transition focus-visible:ring-2 focus-visible:ring-current ${active?"bg-white/25 shadow-sm":"opacity-75 hover:bg-white/15 hover:opacity-100"}`}><NavIcon name={item.icon}/><span className="w-full truncate">{item.shortLabel}</span></button>})}</nav>
  <nav aria-label="Primary navigation" className={`order-3 hidden w-full items-center gap-4 border-t border-current/10 pt-3 text-sm font-medium sm:flex sm:justify-center lg:order-none lg:w-auto lg:gap-8 lg:border-0 lg:pt-0 ${text}`}>{navItems.map(item=><div key={item.label} className="shrink-0"><NavItem {...item} active={location.pathname===item.to.split("?")[0]} textColor={text} activeColor={text}/></div>)}</nav>
  <div className="flex shrink-0 items-center gap-1 sm:gap-4"><Badge className={white?"bg-slate-100 text-slate-800 ring-1 ring-inset ring-slate-200":"bg-white/20 text-white"}>{wallet?<span aria-label={`${lives} of ${max} lives remaining`}>{Array.from({length:max},(_,index)=><span key={index} className={index<lives?"text-red-500":white?"text-slate-400":"text-white/70"}>{index<lives?"♥":"♡"}</span>)}</span>:<span className="inline-block w-8 animate-pulse text-center opacity-50 sm:w-10" aria-label="Loading lives">•••</span>}</Badge><Badge className={white?"bg-slate-100 font-semibold text-slate-800 ring-1 ring-inset ring-slate-200":"bg-white/20 text-white"}>🪙 <span>{wallet?Number(wallet.coins_count||0).toLocaleString():"—"}</span></Badge><button aria-label={`Notifications${unread?`, ${unread} unread`:""}`} onClick={()=>navigate("/notification")} className={`relative grid h-8 w-8 place-items-center rounded-full text-sm transition hover:scale-105 sm:h-10 sm:w-10 sm:text-base ${white?"bg-slate-100 text-slate-800 ring-1 ring-inset ring-slate-200":"bg-white/20 text-white"}`}>🔔{unread>0&&<span className="absolute -right-1 -top-1 grid min-h-4 min-w-4 place-items-center rounded-full bg-red-500 px-1 text-[9px] font-black text-white sm:min-h-5 sm:min-w-5 sm:text-[10px]">{unread>99?"99+":unread}</span>}</button></div>
 </header>;
}
